// Code generated by mockery. DO NOT EDIT.

package healthcheck

import mock "github.com/stretchr/testify/mock"

// MockHCOption is an autogenerated mock type for the HCOption type
type MockHCOption struct {
	mock.Mock
}

type MockHCOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHCOption) EXPECT() *MockHCOption_Expecter {
	return &MockHCOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: check
func (_m *MockHCOption) Execute(check *healthcheck.healthCheck) {
	_m.Called(check)
}

// MockHCOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockHCOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - check *healthcheck.healthCheck
func (_e *MockHCOption_Expecter) Execute(check interface{}) *MockHCOption_Execute_Call {
	return &MockHCOption_Execute_Call{Call: _e.mock.On("Execute", check)}
}

func (_c *MockHCOption_Execute_Call) Run(run func(check *healthcheck.healthCheck)) *MockHCOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*healthcheck.healthCheck))
	})
	return _c
}

func (_c *MockHCOption_Execute_Call) Return() *MockHCOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHCOption_Execute_Call) RunAndReturn(run func(*healthcheck.healthCheck)) *MockHCOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHCOption creates a new instance of MockHCOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHCOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHCOption {
	mock := &MockHCOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
