// Code generated by mockery. DO NOT EDIT.

package healthcheck

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockMetrics is an autogenerated mock type for the Metrics type
type MockMetrics struct {
	mock.Mock
}

type MockMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetrics) EXPECT() *MockMetrics_Expecter {
	return &MockMetrics_Expecter{mock: &_m.Mock}
}

// HandlerMetrics provides a mock function with given fields:
func (_m *MockMetrics) HandlerMetrics() http.Handler {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HandlerMetrics")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func() http.Handler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// MockMetrics_HandlerMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlerMetrics'
type MockMetrics_HandlerMetrics_Call struct {
	*mock.Call
}

// HandlerMetrics is a helper method to define mock.On call
func (_e *MockMetrics_Expecter) HandlerMetrics() *MockMetrics_HandlerMetrics_Call {
	return &MockMetrics_HandlerMetrics_Call{Call: _e.mock.On("HandlerMetrics")}
}

func (_c *MockMetrics_HandlerMetrics_Call) Run(run func()) *MockMetrics_HandlerMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetrics_HandlerMetrics_Call) Return(_a0 http.Handler) *MockMetrics_HandlerMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetrics_HandlerMetrics_Call) RunAndReturn(run func() http.Handler) *MockMetrics_HandlerMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: name
func (_m *MockMetrics) Register(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetrics_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockMetrics_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - name string
func (_e *MockMetrics_Expecter) Register(name interface{}) *MockMetrics_Register_Call {
	return &MockMetrics_Register_Call{Call: _e.mock.On("Register", name)}
}

func (_c *MockMetrics_Register_Call) Run(run func(name string)) *MockMetrics_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMetrics_Register_Call) Return(_a0 error) *MockMetrics_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetrics_Register_Call) RunAndReturn(run func(string) error) *MockMetrics_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: name, t, err
func (_m *MockMetrics) Save(name string, t float64, err error) error {
	ret := _m.Called(name, t, err)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, error) error); ok {
		r0 = rf(name, t, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetrics_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMetrics_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - name string
//   - t float64
//   - err error
func (_e *MockMetrics_Expecter) Save(name interface{}, t interface{}, err interface{}) *MockMetrics_Save_Call {
	return &MockMetrics_Save_Call{Call: _e.mock.On("Save", name, t, err)}
}

func (_c *MockMetrics_Save_Call) Run(run func(name string, t float64, err error)) *MockMetrics_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64), args[2].(error))
	})
	return _c
}

func (_c *MockMetrics_Save_Call) Return(_a0 error) *MockMetrics_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetrics_Save_Call) RunAndReturn(run func(string, float64, error) error) *MockMetrics_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetrics creates a new instance of MockMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetrics {
	mock := &MockMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
