// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package healthcheck

import (
	"net/http"

	"github.com/AOzhogin/healthcheck"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthCheck creates a new instance of MockHealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheck {
	mock := &MockHealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthCheck is an autogenerated mock type for the HealthCheck type
type MockHealthCheck struct {
	mock.Mock
}

type MockHealthCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheck) EXPECT() *MockHealthCheck_Expecter {
	return &MockHealthCheck_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockHealthCheck
func (_mock *MockHealthCheck) Add(name string, notes string, e healthcheck.HCFunc) error {
	ret := _mock.Called(name, notes, e)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, healthcheck.HCFunc) error); ok {
		r0 = returnFunc(name, notes, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthCheck_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockHealthCheck_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - name string
//   - notes string
//   - e healthcheck.HCFunc
func (_e *MockHealthCheck_Expecter) Add(name interface{}, notes interface{}, e interface{}) *MockHealthCheck_Add_Call {
	return &MockHealthCheck_Add_Call{Call: _e.mock.On("Add", name, notes, e)}
}

func (_c *MockHealthCheck_Add_Call) Run(run func(name string, notes string, e healthcheck.HCFunc)) *MockHealthCheck_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 healthcheck.HCFunc
		if args[2] != nil {
			arg2 = args[2].(healthcheck.HCFunc)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHealthCheck_Add_Call) Return(err error) *MockHealthCheck_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthCheck_Add_Call) RunAndReturn(run func(name string, notes string, e healthcheck.HCFunc) error) *MockHealthCheck_Add_Call {
	_c.Call.Return(run)
	return _c
}

// HandlerHealth provides a mock function for the type MockHealthCheck
func (_mock *MockHealthCheck) HandlerHealth(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHealthCheck_HandlerHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlerHealth'
type MockHealthCheck_HandlerHealth_Call struct {
	*mock.Call
}

// HandlerHealth is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHealthCheck_Expecter) HandlerHealth(w interface{}, r interface{}) *MockHealthCheck_HandlerHealth_Call {
	return &MockHealthCheck_HandlerHealth_Call{Call: _e.mock.On("HandlerHealth", w, r)}
}

func (_c *MockHealthCheck_HandlerHealth_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHealthCheck_HandlerHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHealthCheck_HandlerHealth_Call) Return() *MockHealthCheck_HandlerHealth_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_HandlerHealth_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHealthCheck_HandlerHealth_Call {
	_c.Run(run)
	return _c
}

// HandlerMetrics provides a mock function for the type MockHealthCheck
func (_mock *MockHealthCheck) HandlerMetrics(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHealthCheck_HandlerMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlerMetrics'
type MockHealthCheck_HandlerMetrics_Call struct {
	*mock.Call
}

// HandlerMetrics is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHealthCheck_Expecter) HandlerMetrics(w interface{}, r interface{}) *MockHealthCheck_HandlerMetrics_Call {
	return &MockHealthCheck_HandlerMetrics_Call{Call: _e.mock.On("HandlerMetrics", w, r)}
}

func (_c *MockHealthCheck_HandlerMetrics_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHealthCheck_HandlerMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHealthCheck_HandlerMetrics_Call) Return() *MockHealthCheck_HandlerMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_HandlerMetrics_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHealthCheck_HandlerMetrics_Call {
	_c.Run(run)
	return _c
}

// HandlerPProf provides a mock function for the type MockHealthCheck
func (_mock *MockHealthCheck) HandlerPProf(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHealthCheck_HandlerPProf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlerPProf'
type MockHealthCheck_HandlerPProf_Call struct {
	*mock.Call
}

// HandlerPProf is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHealthCheck_Expecter) HandlerPProf(w interface{}, r interface{}) *MockHealthCheck_HandlerPProf_Call {
	return &MockHealthCheck_HandlerPProf_Call{Call: _e.mock.On("HandlerPProf", w, r)}
}

func (_c *MockHealthCheck_HandlerPProf_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHealthCheck_HandlerPProf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHealthCheck_HandlerPProf_Call) Return() *MockHealthCheck_HandlerPProf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_HandlerPProf_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHealthCheck_HandlerPProf_Call {
	_c.Run(run)
	return _c
}

// SetHandlerLive provides a mock function for the type MockHealthCheck
func (_mock *MockHealthCheck) SetHandlerLive(handler http.HandlerFunc) {
	_mock.Called(handler)
	return
}

// MockHealthCheck_SetHandlerLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHandlerLive'
type MockHealthCheck_SetHandlerLive_Call struct {
	*mock.Call
}

// SetHandlerLive is a helper method to define mock.On call
//   - handler http.HandlerFunc
func (_e *MockHealthCheck_Expecter) SetHandlerLive(handler interface{}) *MockHealthCheck_SetHandlerLive_Call {
	return &MockHealthCheck_SetHandlerLive_Call{Call: _e.mock.On("SetHandlerLive", handler)}
}

func (_c *MockHealthCheck_SetHandlerLive_Call) Run(run func(handler http.HandlerFunc)) *MockHealthCheck_SetHandlerLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.HandlerFunc
		if args[0] != nil {
			arg0 = args[0].(http.HandlerFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthCheck_SetHandlerLive_Call) Return() *MockHealthCheck_SetHandlerLive_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_SetHandlerLive_Call) RunAndReturn(run func(handler http.HandlerFunc)) *MockHealthCheck_SetHandlerLive_Call {
	_c.Run(run)
	return _c
}

// SetHandlerReady provides a mock function for the type MockHealthCheck
func (_mock *MockHealthCheck) SetHandlerReady(handler http.HandlerFunc) {
	_mock.Called(handler)
	return
}

// MockHealthCheck_SetHandlerReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHandlerReady'
type MockHealthCheck_SetHandlerReady_Call struct {
	*mock.Call
}

// SetHandlerReady is a helper method to define mock.On call
//   - handler http.HandlerFunc
func (_e *MockHealthCheck_Expecter) SetHandlerReady(handler interface{}) *MockHealthCheck_SetHandlerReady_Call {
	return &MockHealthCheck_SetHandlerReady_Call{Call: _e.mock.On("SetHandlerReady", handler)}
}

func (_c *MockHealthCheck_SetHandlerReady_Call) Run(run func(handler http.HandlerFunc)) *MockHealthCheck_SetHandlerReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.HandlerFunc
		if args[0] != nil {
			arg0 = args[0].(http.HandlerFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthCheck_SetHandlerReady_Call) Return() *MockHealthCheck_SetHandlerReady_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_SetHandlerReady_Call) RunAndReturn(run func(handler http.HandlerFunc)) *MockHealthCheck_SetHandlerReady_Call {
	_c.Run(run)
	return _c
}

// SetHandlerStartup provides a mock function for the type MockHealthCheck
func (_mock *MockHealthCheck) SetHandlerStartup(handler http.HandlerFunc) {
	_mock.Called(handler)
	return
}

// MockHealthCheck_SetHandlerStartup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHandlerStartup'
type MockHealthCheck_SetHandlerStartup_Call struct {
	*mock.Call
}

// SetHandlerStartup is a helper method to define mock.On call
//   - handler http.HandlerFunc
func (_e *MockHealthCheck_Expecter) SetHandlerStartup(handler interface{}) *MockHealthCheck_SetHandlerStartup_Call {
	return &MockHealthCheck_SetHandlerStartup_Call{Call: _e.mock.On("SetHandlerStartup", handler)}
}

func (_c *MockHealthCheck_SetHandlerStartup_Call) Run(run func(handler http.HandlerFunc)) *MockHealthCheck_SetHandlerStartup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.HandlerFunc
		if args[0] != nil {
			arg0 = args[0].(http.HandlerFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthCheck_SetHandlerStartup_Call) Return() *MockHealthCheck_SetHandlerStartup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_SetHandlerStartup_Call) RunAndReturn(run func(handler http.HandlerFunc)) *MockHealthCheck_SetHandlerStartup_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MockHealthCheck
func (_mock *MockHealthCheck) Shutdown() {
	_mock.Called()
	return
}

// MockHealthCheck_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockHealthCheck_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockHealthCheck_Expecter) Shutdown() *MockHealthCheck_Shutdown_Call {
	return &MockHealthCheck_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockHealthCheck_Shutdown_Call) Run(run func()) *MockHealthCheck_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheck_Shutdown_Call) Return() *MockHealthCheck_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_Shutdown_Call) RunAndReturn(run func()) *MockHealthCheck_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockHealthCheck
func (_mock *MockHealthCheck) Start() {
	_mock.Called()
	return
}

// MockHealthCheck_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockHealthCheck_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockHealthCheck_Expecter) Start() *MockHealthCheck_Start_Call {
	return &MockHealthCheck_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockHealthCheck_Start_Call) Run(run func()) *MockHealthCheck_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheck_Start_Call) Return() *MockHealthCheck_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_Start_Call) RunAndReturn(run func()) *MockHealthCheck_Start_Call {
	_c.Run(run)
	return _c
}

// NewMockMetrics creates a new instance of MockMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetrics {
	mock := &MockMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetrics is an autogenerated mock type for the Metrics type
type MockMetrics struct {
	mock.Mock
}

type MockMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetrics) EXPECT() *MockMetrics_Expecter {
	return &MockMetrics_Expecter{mock: &_m.Mock}
}

// HandlerMetrics provides a mock function for the type MockMetrics
func (_mock *MockMetrics) HandlerMetrics() http.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HandlerMetrics")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func() http.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// MockMetrics_HandlerMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlerMetrics'
type MockMetrics_HandlerMetrics_Call struct {
	*mock.Call
}

// HandlerMetrics is a helper method to define mock.On call
func (_e *MockMetrics_Expecter) HandlerMetrics() *MockMetrics_HandlerMetrics_Call {
	return &MockMetrics_HandlerMetrics_Call{Call: _e.mock.On("HandlerMetrics")}
}

func (_c *MockMetrics_HandlerMetrics_Call) Run(run func()) *MockMetrics_HandlerMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetrics_HandlerMetrics_Call) Return(handler http.Handler) *MockMetrics_HandlerMetrics_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockMetrics_HandlerMetrics_Call) RunAndReturn(run func() http.Handler) *MockMetrics_HandlerMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockMetrics
func (_mock *MockMetrics) Register(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetrics_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockMetrics_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - name string
func (_e *MockMetrics_Expecter) Register(name interface{}) *MockMetrics_Register_Call {
	return &MockMetrics_Register_Call{Call: _e.mock.On("Register", name)}
}

func (_c *MockMetrics_Register_Call) Run(run func(name string)) *MockMetrics_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetrics_Register_Call) Return(err error) *MockMetrics_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetrics_Register_Call) RunAndReturn(run func(name string) error) *MockMetrics_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockMetrics
func (_mock *MockMetrics) Save(name string, t float64, err error) error {
	ret := _mock.Called(name, t, err)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, float64, error) error); ok {
		r0 = returnFunc(name, t, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetrics_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMetrics_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - name string
//   - t float64
//   - err error
func (_e *MockMetrics_Expecter) Save(name interface{}, t interface{}, err interface{}) *MockMetrics_Save_Call {
	return &MockMetrics_Save_Call{Call: _e.mock.On("Save", name, t, err)}
}

func (_c *MockMetrics_Save_Call) Run(run func(name string, t float64, err error)) *MockMetrics_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetrics_Save_Call) Return(err1 error) *MockMetrics_Save_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockMetrics_Save_Call) RunAndReturn(run func(name string, t float64, err error) error) *MockMetrics_Save_Call {
	_c.Call.Return(run)
	return _c
}
