// Code generated by mockery. DO NOT EDIT.

package healthcheck

import (
	http "net/http"

	healthcheck "github.com/AOzhogin/healthcheck"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheck is an autogenerated mock type for the HealthCheck type
type MockHealthCheck struct {
	mock.Mock
}

type MockHealthCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheck) EXPECT() *MockHealthCheck_Expecter {
	return &MockHealthCheck_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: name, notes, e
func (_m *MockHealthCheck) Add(name string, notes string, e healthcheck.HCFunc) error {
	ret := _m.Called(name, notes, e)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, healthcheck.HCFunc) error); ok {
		r0 = rf(name, notes, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthCheck_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockHealthCheck_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - name string
//   - notes string
//   - e healthcheck.HCFunc
func (_e *MockHealthCheck_Expecter) Add(name interface{}, notes interface{}, e interface{}) *MockHealthCheck_Add_Call {
	return &MockHealthCheck_Add_Call{Call: _e.mock.On("Add", name, notes, e)}
}

func (_c *MockHealthCheck_Add_Call) Run(run func(name string, notes string, e healthcheck.HCFunc)) *MockHealthCheck_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(healthcheck.HCFunc))
	})
	return _c
}

func (_c *MockHealthCheck_Add_Call) Return(_a0 error) *MockHealthCheck_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthCheck_Add_Call) RunAndReturn(run func(string, string, healthcheck.HCFunc) error) *MockHealthCheck_Add_Call {
	_c.Call.Return(run)
	return _c
}

// HandlerHealth provides a mock function with given fields: w, r
func (_m *MockHealthCheck) HandlerHealth(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MockHealthCheck_HandlerHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlerHealth'
type MockHealthCheck_HandlerHealth_Call struct {
	*mock.Call
}

// HandlerHealth is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHealthCheck_Expecter) HandlerHealth(w interface{}, r interface{}) *MockHealthCheck_HandlerHealth_Call {
	return &MockHealthCheck_HandlerHealth_Call{Call: _e.mock.On("HandlerHealth", w, r)}
}

func (_c *MockHealthCheck_HandlerHealth_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHealthCheck_HandlerHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockHealthCheck_HandlerHealth_Call) Return() *MockHealthCheck_HandlerHealth_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_HandlerHealth_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockHealthCheck_HandlerHealth_Call {
	_c.Call.Return(run)
	return _c
}

// HandlerMetrics provides a mock function with given fields: w, r
func (_m *MockHealthCheck) HandlerMetrics(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MockHealthCheck_HandlerMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlerMetrics'
type MockHealthCheck_HandlerMetrics_Call struct {
	*mock.Call
}

// HandlerMetrics is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHealthCheck_Expecter) HandlerMetrics(w interface{}, r interface{}) *MockHealthCheck_HandlerMetrics_Call {
	return &MockHealthCheck_HandlerMetrics_Call{Call: _e.mock.On("HandlerMetrics", w, r)}
}

func (_c *MockHealthCheck_HandlerMetrics_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHealthCheck_HandlerMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockHealthCheck_HandlerMetrics_Call) Return() *MockHealthCheck_HandlerMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_HandlerMetrics_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockHealthCheck_HandlerMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields:
func (_m *MockHealthCheck) Shutdown() {
	_m.Called()
}

// MockHealthCheck_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockHealthCheck_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockHealthCheck_Expecter) Shutdown() *MockHealthCheck_Shutdown_Call {
	return &MockHealthCheck_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockHealthCheck_Shutdown_Call) Run(run func()) *MockHealthCheck_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheck_Shutdown_Call) Return() *MockHealthCheck_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_Shutdown_Call) RunAndReturn(run func()) *MockHealthCheck_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields:
func (_m *MockHealthCheck) Start() {
	_m.Called()
}

// MockHealthCheck_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockHealthCheck_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockHealthCheck_Expecter) Start() *MockHealthCheck_Start_Call {
	return &MockHealthCheck_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockHealthCheck_Start_Call) Run(run func()) *MockHealthCheck_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheck_Start_Call) Return() *MockHealthCheck_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthCheck_Start_Call) RunAndReturn(run func()) *MockHealthCheck_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheck creates a new instance of MockHealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheck {
	mock := &MockHealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
